FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:fe3c1ed472bb0964c100f06aa9b1759f5ed84e0dfe6904d60f6a82159d3c7ae4 AS build

RUN apt-get update && \
    apt-get install -y capnproto libcapnp-dev && \
    rm -rf /var/lib/apt/lists/*

COPY firehorse /app/firehorse
COPY network.proto /app

WORKDIR /app/firehorse

RUN dotnet restore
RUN dotnet publish

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:9.0@sha256:9d42d7d4d892e2afc571884e9b67f3b1ebb361166ee14151fc6d1bd539cbfeb3

WORKDIR /app
COPY --from=build /app/firehorse/bin/Release/net9.0/ .

CMD ["dotnet", "/app/Firehorse.dll"]
